site_name: PHYS281

site_author: Matthew Pitkin

theme:
  name: material

  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: 'index.md'
  - Tutorial:
    - Basic data types: 'demo-data-types.md'
    - Compound data types: 'demo-compound-data-types.md'
    - Python functions: 'demo-functions.md'
    - Python classes: 'demo-classes.md'
    - Error checking and debugging: 'demo-error-checking.md'
    - NumPy basics: 'demo-numpy.md'
  - glossary.md

docs_dir: 'docs'

extra_css:
  - css/tooltips.css

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - mdtooltipslink:
      header: True
  - pymdownx.highlight:
      use_pygments: True
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
