site_name: PHYS281

site_author: Matthew Pitkin

theme:
  name: material

  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: 'index.md'
  - Tutorial:
    - Getting started:
       - Installing Anaconda: 'demo-anaconda.md'
       - Installing VS code: 'demo-vs-code.md'
       - Using a terminal: 'demo-terminal.md'
       - The Python terminal: 'demo-python-terminal.md'
    - Python basics:
       - Writing scripts: 'demo-scripts.md'
       - Importing modules: 'demo-importing-modules.md'
       - Basic data types: 'demo-data-types.md'
       - Compound data types: 'demo-compound-data-types.md'
       - Built-in functions: 'demo-built-in-functions.md'
       - Flow control: 'demo-flow-control.md'
       - Python functions: 'demo-functions.md'
       - Python classes: 'demo-classes.md'
    - Further information:
       - Error checking and debugging: 'demo-error-checking.md'
       - NumPy basics: 'demo-numpy.md'
       - Reading and writing data: 'demo-io.md'
       - Basic plotting with Matplotlib: 'demo-matplotlib.md'
    - glossary.md

docs_dir: 'docs'

extra_css:
  - css/tooltips.css

extra_javascript:
  - https://unpkg.com/@popperjs/core@2
  - https://unpkg.com/tippy.js@6
  - javascript/glossary.js

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - mdtooltipslink:
      js_file: docs/javascript/glossary.js
  - pymdownx.highlight:
      use_pygments: True
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
